#!/bin/bash
TEMPLATE_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

eval SOURCE_DIRECTORY="~/Library/Developer/Xcode/Templates/File\ Templates/"

echo "Installing templates to:"
echo "$SOURCE_DIRECTORY"

if [ -d "$SOURCE_DIRECTORY" ]; then
        eval cd '"$SOURCE_DIRECTORY"'
        eval mkdir "VIPER"
        eval cd "VIPER"
        echo "Creating symbolic links to"
        echo ${TEMPLATE_DIRECTORY}

        sudo ln -sfn "${TEMPLATE_DIRECTORY}/VIPER.xctemplate" "VIPER.xctemplate"
        sudo ln -sfn "${TEMPLATE_DIRECTORY}/VIPER Tests.xctemplate" "VIPER Tests.xctemplate"

        echo "Done"
else
        echo "Uh OHHHH that source directory does not exist!!!"
        echo "Aborting. Please check your Xcode app path and try again"
fi
